use super::behavior::CardBehavior;
use super::impls::{
    c01_afternoon::C01AfternoonNap, c02_static::C02StaticNoise, c03_seagull::C03SeagullAttack,
    c04_slippery::C04SlipperyDeck, c05_rain::C05PeppernutRain, c06_waves::C06HighWaves,
    c07_costume::C07CostumeParty, c08_mice::C08MicePlague, c09_short_circuit::C09ShortCircuit,
    c10_leak::C10Leak, c11_mutiny::C11Mutiny, c12_fog::C12FogBank, c13_anchor::C13AnchorStuck,
    c14_jammed::C14JammedCannon, c15_man_overboard::C15ManOverboard,
    c16_headwind::C16StrongHeadwind, c17_listing::C17Listing, c18_clogged::C18CloggedPipe,
    c19_attack_wave::C19AttackWave, c21_sing::C21SingASong, c23_no_light::C23NoLight,
    c24_lucky_dip::C24LuckyDip, c25_panic::C25Panic, c26_seasick::C26Seasick,
    c27_alarm::C27WailingAlarm, c28_anchor_loose::C28AnchorLoose, c29_rudderless::C29Rudderless,
    c30_big_leak::C30BigLeak, c31_blockade::C31Blockade, c32_weird_gifts::C32WeirdGifts,
    c33_flu::C33FluWave, c34_dough::C34MonsterDough, c35_stowaway::C35Stowaway,
    c36_turbo::C36TurboMode, c37_recipe::C37Recipe, c38_golden_nut::C38GoldenNut,
    c39_staff::C39TheStaff, c40_sticky::C40StickyFloor, c41_present::C41Present,
    c42_book::C42TheBook, c43_sugar::C43SugarRush, c44_clamp::C44WheelClamp,
    c45_shoe::C45ShoeSetting, c46_amerigo::C46Amerigo, c47_tantrum::C47Tantrum,
    c48_silent::C48SilentForce, c49_falling::C49FallingGift, c50_overheating::C50Overheating,
    c51_falsenote::C51FalseNote, c52_pressure::C52HighPressure, c53_lightsout::C53LightsOut,
};
use crate::types::{Card, CardId};

pub fn get_behavior(card_id: CardId) -> Box<dyn CardBehavior> {
    match card_id {
        CardId::AfternoonNap => Box::new(C01AfternoonNap),
        CardId::StaticNoise => Box::new(C02StaticNoise),
        CardId::SeagullAttack => Box::new(C03SeagullAttack),
        CardId::SlipperyDeck => Box::new(C04SlipperyDeck),
        CardId::PeppernutRain => Box::new(C05PeppernutRain),
        CardId::HighWaves => Box::new(C06HighWaves),
        CardId::CostumeParty => Box::new(C07CostumeParty),
        CardId::MicePlague => Box::new(C08MicePlague),
        CardId::ShortCircuit => Box::new(C09ShortCircuit),
        CardId::Leak => Box::new(C10Leak),
        CardId::Mutiny => Box::new(C11Mutiny),
        CardId::FogBank => Box::new(C12FogBank),
        CardId::AnchorStuck => Box::new(C13AnchorStuck),
        CardId::JammedCannon => Box::new(C14JammedCannon),
        CardId::ManOverboard => Box::new(C15ManOverboard),
        CardId::StrongHeadwind => Box::new(C16StrongHeadwind),
        CardId::Listing => Box::new(C17Listing),
        CardId::CloggedPipe => Box::new(C18CloggedPipe),
        CardId::AttackWave => Box::new(C19AttackWave),
        CardId::SingASong => Box::new(C21SingASong),
        CardId::NoLight => Box::new(C23NoLight),
        CardId::LuckyDip => Box::new(C24LuckyDip),
        CardId::Panic => Box::new(C25Panic),
        CardId::Seasick => Box::new(C26Seasick),
        CardId::WailingAlarm => Box::new(C27WailingAlarm),
        CardId::AnchorLoose => Box::new(C28AnchorLoose),
        CardId::Rudderless => Box::new(C29Rudderless),
        CardId::BigLeak => Box::new(C30BigLeak),
        CardId::Blockade => Box::new(C31Blockade),
        CardId::WeirdGifts => Box::new(C32WeirdGifts),
        CardId::FluWave => Box::new(C33FluWave),
        CardId::MonsterDough => Box::new(C34MonsterDough),
        CardId::Stowaway => Box::new(C35Stowaway),
        CardId::TurboMode => Box::new(C36TurboMode),
        CardId::Recipe => Box::new(C37Recipe),
        CardId::GoldenNut => Box::new(C38GoldenNut),
        CardId::TheStaff => Box::new(C39TheStaff),
        CardId::StickyFloor => Box::new(C40StickyFloor),
        CardId::Present => Box::new(C41Present),
        CardId::TheBook => Box::new(C42TheBook),
        CardId::SugarRush => Box::new(C43SugarRush),
        CardId::WheelClamp => Box::new(C44WheelClamp),
        CardId::ShoeSetting => Box::new(C45ShoeSetting),
        CardId::Amerigo => Box::new(C46Amerigo),
        CardId::Tantrum => Box::new(C47Tantrum),
        CardId::SilentForce => Box::new(C48SilentForce),
        CardId::FallingGift => Box::new(C49FallingGift),
        CardId::Overheating => Box::new(C50Overheating),
        CardId::FalseNote => Box::new(C51FalseNote),
        CardId::HighPressure => Box::new(C52HighPressure),
        CardId::LightsOut => Box::new(C53LightsOut),
    }
}

// Deterministic List of ALL IDs
const ALL_IDS: &[CardId] = &[
    CardId::AfternoonNap,
    CardId::StaticNoise,
    CardId::SeagullAttack,
    CardId::SlipperyDeck,
    CardId::PeppernutRain,
    CardId::HighWaves,
    CardId::CostumeParty,
    CardId::MicePlague,
    CardId::ShortCircuit,
    CardId::Leak,
    CardId::Mutiny,
    CardId::FogBank,
    CardId::AnchorStuck,
    CardId::JammedCannon,
    CardId::ManOverboard,
    CardId::StrongHeadwind,
    CardId::Listing,
    CardId::CloggedPipe,
    CardId::AttackWave,
    CardId::SingASong,
    CardId::NoLight,
    CardId::LuckyDip,
    CardId::Panic,
    CardId::Seasick,
    CardId::WailingAlarm,
    CardId::AnchorLoose,
    CardId::Rudderless,
    CardId::BigLeak,
    CardId::Blockade,
    CardId::WeirdGifts,
    CardId::FluWave,
    CardId::MonsterDough,
    CardId::Stowaway,
    CardId::TurboMode,
    CardId::Recipe,
    CardId::GoldenNut,
    CardId::TheStaff,
    CardId::StickyFloor,
    CardId::Present,
    CardId::TheBook,
    CardId::SugarRush,
    CardId::WheelClamp,
    CardId::ShoeSetting,
    CardId::Amerigo,
    CardId::Tantrum,
    CardId::SilentForce,
    CardId::FallingGift,
    CardId::Overheating,
    CardId::FalseNote,
    CardId::HighPressure,
    CardId::LightsOut,
];

pub fn get_all_cards() -> Vec<Card> {
    ALL_IDS
        .iter()
        .map(|&id| get_behavior(id).get_struct())
        .collect()
}
