use super::behavior::CardBehavior;
use super::impls::{
    card_afternoon::AfternoonNapCard, card_alarm::WailingAlarmCard, card_amerigo::AmerigoCard,
    card_anchor::AnchorStuckCard, card_anchor_loose::AnchorLooseCard,
    card_attack_wave::AttackWaveCard, card_big_leak::BigLeakCard, card_blockade::BlockadeCard,
    card_book::TheBookCard, card_clamp::WheelClampCard, card_clogged::CloggedPipeCard,
    card_costume::CostumePartyCard, card_dough::MonsterDoughCard, card_falling::FallingGiftCard,
    card_falsenote::FalseNoteCard, card_flu::FluWaveCard, card_fog::FogBankCard,
    card_golden_nut::GoldenNutCard, card_headwind::StrongHeadwindCard,
    card_jammed::JammedCannonCard, card_leak::LeakCard, card_lightsout::LightsOutCard,
    card_listing::ListingCard, card_lucky_dip::LuckyDipCard, card_man_overboard::ManOverboardCard,
    card_mice::MicePlagueCard, card_mutiny::MutinyCard, card_no_light::NoLightCard,
    card_overheating::OverheatingCard, card_panic::PanicCard, card_present::PresentCard,
    card_pressure::HighPressureCard, card_rain::PeppernutRainCard, card_recipe::RecipeCard,
    card_rudderless::RudderlessCard, card_seagull::SeagullAttackCard, card_seasick::SeasickCard,
    card_shoe::ShoeSettingCard, card_short_circuit::ShortCircuitCard, card_silent::SilentForceCard,
    card_sing::SingASongCard, card_slippery::SlipperyDeckCard, card_staff::TheStaffCard,
    card_static::StaticNoiseCard, card_sticky::StickyFloorCard, card_stowaway::StowawayCard,
    card_sugar::SugarRushCard, card_turbo::TurboModeCard, card_waves::HighWavesCard,
    card_weird_gifts::WeirdGiftsCard,
};
use crate::types::{Card, CardId};

pub fn get_behavior(card_id: CardId) -> Box<dyn CardBehavior> {
    match card_id {
        // sorted start
        CardId::AfternoonNap => Box::new(AfternoonNapCard),
        CardId::Amerigo => Box::new(AmerigoCard),
        CardId::AnchorLoose => Box::new(AnchorLooseCard),
        CardId::AnchorStuck => Box::new(AnchorStuckCard),
        CardId::AttackWave => Box::new(AttackWaveCard),
        CardId::BigLeak => Box::new(BigLeakCard),
        CardId::Blockade => Box::new(BlockadeCard),
        CardId::CloggedPipe => Box::new(CloggedPipeCard),
        CardId::CostumeParty => Box::new(CostumePartyCard),
        CardId::FallingGift => Box::new(FallingGiftCard),
        CardId::FalseNote => Box::new(FalseNoteCard),
        CardId::FluWave => Box::new(FluWaveCard),
        CardId::FogBank => Box::new(FogBankCard),
        CardId::GoldenNut => Box::new(GoldenNutCard),
        CardId::HighPressure => Box::new(HighPressureCard),
        CardId::HighWaves => Box::new(HighWavesCard),
        CardId::JammedCannon => Box::new(JammedCannonCard),
        CardId::Leak => Box::new(LeakCard),
        CardId::LightsOut => Box::new(LightsOutCard),
        CardId::Listing => Box::new(ListingCard),
        CardId::LuckyDip => Box::new(LuckyDipCard),
        CardId::ManOverboard => Box::new(ManOverboardCard),
        CardId::MicePlague => Box::new(MicePlagueCard),
        CardId::MonsterDough => Box::new(MonsterDoughCard),
        CardId::Mutiny => Box::new(MutinyCard),
        CardId::NoLight => Box::new(NoLightCard),
        CardId::Overheating => Box::new(OverheatingCard),
        CardId::Panic => Box::new(PanicCard),
        CardId::PeppernutRain => Box::new(PeppernutRainCard),
        CardId::Present => Box::new(PresentCard),
        CardId::Recipe => Box::new(RecipeCard),
        CardId::Rudderless => Box::new(RudderlessCard),
        CardId::SeagullAttack => Box::new(SeagullAttackCard),
        CardId::Seasick => Box::new(SeasickCard),
        CardId::ShoeSetting => Box::new(ShoeSettingCard),
        CardId::ShortCircuit => Box::new(ShortCircuitCard),
        CardId::SilentForce => Box::new(SilentForceCard),
        CardId::SingASong => Box::new(SingASongCard),
        CardId::SlipperyDeck => Box::new(SlipperyDeckCard),
        CardId::StaticNoise => Box::new(StaticNoiseCard),
        CardId::StickyFloor => Box::new(StickyFloorCard),
        CardId::Stowaway => Box::new(StowawayCard),
        CardId::StrongHeadwind => Box::new(StrongHeadwindCard),
        CardId::SugarRush => Box::new(SugarRushCard),
        CardId::TheBook => Box::new(TheBookCard),
        CardId::TheStaff => Box::new(TheStaffCard),
        CardId::TurboMode => Box::new(TurboModeCard),
        CardId::WailingAlarm => Box::new(WailingAlarmCard),
        CardId::WeirdGifts => Box::new(WeirdGiftsCard),
        CardId::WheelClamp => Box::new(WheelClampCard),
        // sorted end
    }
}

// Deterministic List of ALL IDs
const ALL_IDS: &[CardId] = &[
    // keep-sorted start
    CardId::AfternoonNap,
    CardId::Amerigo,
    CardId::AnchorLoose,
    CardId::AnchorStuck,
    CardId::AttackWave,
    CardId::BigLeak,
    CardId::Blockade,
    CardId::CloggedPipe,
    CardId::CostumeParty,
    CardId::FallingGift,
    CardId::FalseNote,
    CardId::FluWave,
    CardId::FogBank,
    CardId::GoldenNut,
    CardId::HighPressure,
    CardId::HighWaves,
    CardId::JammedCannon,
    CardId::Leak,
    CardId::LightsOut,
    CardId::Listing,
    CardId::LuckyDip,
    CardId::ManOverboard,
    CardId::MicePlague,
    CardId::MonsterDough,
    CardId::Mutiny,
    CardId::NoLight,
    CardId::Overheating,
    CardId::Panic,
    CardId::PeppernutRain,
    CardId::Present,
    CardId::Recipe,
    CardId::Rudderless,
    CardId::SeagullAttack,
    CardId::Seasick,
    CardId::ShoeSetting,
    CardId::ShortCircuit,
    CardId::SilentForce,
    CardId::SingASong,
    CardId::SlipperyDeck,
    CardId::StaticNoise,
    CardId::StickyFloor,
    CardId::Stowaway,
    CardId::StrongHeadwind,
    CardId::SugarRush,
    CardId::TheBook,
    CardId::TheStaff,
    CardId::TurboMode,
    CardId::WailingAlarm,
    CardId::WeirdGifts,
    CardId::WheelClamp,
    // keep-sorted end
];

pub fn get_all_cards() -> Vec<Card> {
    ALL_IDS
        .iter()
        .map(|&id| get_behavior(id).get_struct())
        .collect()
}

pub fn get_all_ids() -> Vec<CardId> {
    ALL_IDS.to_vec()
}
