use super::behavior::CardBehavior;
use super::impls::{
    card_afternoon::AfternoonNapCard,
    card_static::StaticNoiseCard,
    card_seagull::SeagullAttackCard,
    card_slippery::SlipperyDeckCard,
    card_rain::PeppernutRainCard,
    card_waves::HighWavesCard,
    card_costume::CostumePartyCard,
    card_mice::MicePlagueCard,
    card_short_circuit::ShortCircuitCard,
    card_leak::LeakCard,
    card_mutiny::MutinyCard,
    card_fog::FogBankCard,
    card_anchor::AnchorStuckCard,
    card_jammed::JammedCannonCard,
    card_man_overboard::ManOverboardCard,
    card_headwind::StrongHeadwindCard,
    card_listing::ListingCard,
    card_clogged::CloggedPipeCard,
    card_attack_wave::AttackWaveCard,
    card_sing::SingASongCard,
    card_no_light::NoLightCard,
    card_lucky_dip::LuckyDipCard,
    card_panic::PanicCard,
    card_seasick::SeasickCard,
    card_alarm::WailingAlarmCard,
    card_anchor_loose::AnchorLooseCard,
    card_rudderless::RudderlessCard,
    card_big_leak::BigLeakCard,
    card_blockade::BlockadeCard,
    card_weird_gifts::WeirdGiftsCard,
    card_flu::FluWaveCard,
    card_dough::MonsterDoughCard,
    card_stowaway::StowawayCard,
    card_turbo::TurboModeCard,
    card_recipe::RecipeCard,
    card_golden_nut::GoldenNutCard,
    card_staff::TheStaffCard,
    card_sticky::StickyFloorCard,
    card_present::PresentCard,
    card_book::TheBookCard,
    card_sugar::SugarRushCard,
    card_clamp::WheelClampCard,
    card_shoe::ShoeSettingCard,
    card_amerigo::AmerigoCard,
    card_tantrum::TantrumCard,
    card_silent::SilentForceCard,
    card_falling::FallingGiftCard,
    card_overheating::OverheatingCard,
    card_falsenote::FalseNoteCard,
    card_pressure::HighPressureCard,
    card_lightsout::LightsOutCard,
};
use crate::types::{Card, CardId};

pub fn get_behavior(card_id: CardId) -> Box<dyn CardBehavior> {
    match card_id {
        CardId::AfternoonNap => Box::new(AfternoonNapCard),
        CardId::StaticNoise => Box::new(StaticNoiseCard),
        CardId::SeagullAttack => Box::new(SeagullAttackCard),
        CardId::SlipperyDeck => Box::new(SlipperyDeckCard),
        CardId::PeppernutRain => Box::new(PeppernutRainCard),
        CardId::HighWaves => Box::new(HighWavesCard),
        CardId::CostumeParty => Box::new(CostumePartyCard),
        CardId::MicePlague => Box::new(MicePlagueCard),
        CardId::ShortCircuit => Box::new(ShortCircuitCard),
        CardId::Leak => Box::new(LeakCard),
        CardId::Mutiny => Box::new(MutinyCard),
        CardId::FogBank => Box::new(FogBankCard),
        CardId::AnchorStuck => Box::new(AnchorStuckCard),
        CardId::JammedCannon => Box::new(JammedCannonCard),
        CardId::ManOverboard => Box::new(ManOverboardCard),
        CardId::StrongHeadwind => Box::new(StrongHeadwindCard),
        CardId::Listing => Box::new(ListingCard),
        CardId::CloggedPipe => Box::new(CloggedPipeCard),
        CardId::AttackWave => Box::new(AttackWaveCard),
        CardId::SingASong => Box::new(SingASongCard),
        CardId::NoLight => Box::new(NoLightCard),
        CardId::LuckyDip => Box::new(LuckyDipCard),
        CardId::Panic => Box::new(PanicCard),
        CardId::Seasick => Box::new(SeasickCard),
        CardId::WailingAlarm => Box::new(WailingAlarmCard),
        CardId::AnchorLoose => Box::new(AnchorLooseCard),
        CardId::Rudderless => Box::new(RudderlessCard),
        CardId::BigLeak => Box::new(BigLeakCard),
        CardId::Blockade => Box::new(BlockadeCard),
        CardId::WeirdGifts => Box::new(WeirdGiftsCard),
        CardId::FluWave => Box::new(FluWaveCard),
        CardId::MonsterDough => Box::new(MonsterDoughCard),
        CardId::Stowaway => Box::new(StowawayCard),
        CardId::TurboMode => Box::new(TurboModeCard),
        CardId::Recipe => Box::new(RecipeCard),
        CardId::GoldenNut => Box::new(GoldenNutCard),
        CardId::TheStaff => Box::new(TheStaffCard),
        CardId::StickyFloor => Box::new(StickyFloorCard),
        CardId::Present => Box::new(PresentCard),
        CardId::TheBook => Box::new(TheBookCard),
        CardId::SugarRush => Box::new(SugarRushCard),
        CardId::WheelClamp => Box::new(WheelClampCard),
        CardId::ShoeSetting => Box::new(ShoeSettingCard),
        CardId::Amerigo => Box::new(AmerigoCard),
        CardId::Tantrum => Box::new(TantrumCard),
        CardId::SilentForce => Box::new(SilentForceCard),
        CardId::FallingGift => Box::new(FallingGiftCard),
        CardId::Overheating => Box::new(OverheatingCard),
        CardId::FalseNote => Box::new(FalseNoteCard),
        CardId::HighPressure => Box::new(HighPressureCard),
        CardId::LightsOut => Box::new(LightsOutCard),
    }
}

// Deterministic List of ALL IDs
const ALL_IDS: &[CardId] = &[
    CardId::AfternoonNap,
    CardId::StaticNoise,
    CardId::SeagullAttack,
    CardId::SlipperyDeck,
    CardId::PeppernutRain,
    CardId::HighWaves,
    CardId::CostumeParty,
    CardId::MicePlague,
    CardId::ShortCircuit,
    CardId::Leak,
    CardId::Mutiny,
    CardId::FogBank,
    CardId::AnchorStuck,
    CardId::JammedCannon,
    CardId::ManOverboard,
    CardId::StrongHeadwind,
    CardId::Listing,
    CardId::CloggedPipe,
    CardId::AttackWave,
    CardId::SingASong,
    CardId::NoLight,
    CardId::LuckyDip,
    CardId::Panic,
    CardId::Seasick,
    CardId::WailingAlarm,
    CardId::AnchorLoose,
    CardId::Rudderless,
    CardId::BigLeak,
    CardId::Blockade,
    CardId::WeirdGifts,
    CardId::FluWave,
    CardId::MonsterDough,
    CardId::Stowaway,
    CardId::TurboMode,
    CardId::Recipe,
    CardId::GoldenNut,
    CardId::TheStaff,
    CardId::StickyFloor,
    CardId::Present,
    CardId::TheBook,
    CardId::SugarRush,
    CardId::WheelClamp,
    CardId::ShoeSetting,
    CardId::Amerigo,
    CardId::Tantrum,
    CardId::SilentForce,
    CardId::FallingGift,
    CardId::Overheating,
    CardId::FalseNote,
    CardId::HighPressure,
    CardId::LightsOut,
];

pub fn get_all_cards() -> Vec<Card> {
    ALL_IDS
        .iter()
        .map(|&id| get_behavior(id).get_struct())
        .collect()
}
